// <auto-generated />
using DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250925161427_1.Initial")]
    partial class _1Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DAL.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Apple iPhone 15",
                            Price = 999m
                        },
                        new
                        {
                            Id = 2,
                            Name = "Samsung Galaxy S23",
                            Price = 899m
                        },
                        new
                        {
                            Id = 3,
                            Name = "Sony WH-1000XM5 Headphones",
                            Price = 349m
                        },
                        new
                        {
                            Id = 4,
                            Name = "Apple MacBook Pro 14",
                            Price = 1999m
                        },
                        new
                        {
                            Id = 5,
                            Name = "Dell XPS 13 Laptop",
                            Price = 1299m
                        },
                        new
                        {
                            Id = 6,
                            Name = "Logitech MX Master 3 Mouse",
                            Price = 99m
                        },
                        new
                        {
                            Id = 7,
                            Name = "Apple iPad Air",
                            Price = 599m
                        },
                        new
                        {
                            Id = 8,
                            Name = "Amazon Kindle Paperwhite",
                            Price = 139m
                        },
                        new
                        {
                            Id = 9,
                            Name = "Google Pixel 8",
                            Price = 799m
                        },
                        new
                        {
                            Id = 10,
                            Name = "Bose SoundLink Speaker",
                            Price = 129m
                        },
                        new
                        {
                            Id = 11,
                            Name = "Nintendo Switch",
                            Price = 299m
                        },
                        new
                        {
                            Id = 12,
                            Name = "PlayStation 5",
                            Price = 499m
                        },
                        new
                        {
                            Id = 13,
                            Name = "Xbox Series X",
                            Price = 499m
                        },
                        new
                        {
                            Id = 14,
                            Name = "Fitbit Charge 6",
                            Price = 149m
                        },
                        new
                        {
                            Id = 15,
                            Name = "GoPro HERO12",
                            Price = 399m
                        },
                        new
                        {
                            Id = 16,
                            Name = "Canon EOS R10 Camera",
                            Price = 979m
                        },
                        new
                        {
                            Id = 17,
                            Name = "Apple Watch Series 9",
                            Price = 399m
                        },
                        new
                        {
                            Id = 18,
                            Name = "Samsung Galaxy Watch 6",
                            Price = 329m
                        },
                        new
                        {
                            Id = 19,
                            Name = "JBL Flip 6 Bluetooth Speaker",
                            Price = 119m
                        },
                        new
                        {
                            Id = 20,
                            Name = "Anker PowerCore 20000mAh",
                            Price = 49m
                        },
                        new
                        {
                            Id = 21,
                            Name = "Razer BlackWidow V4 Keyboard",
                            Price = 179m
                        },
                        new
                        {
                            Id = 22,
                            Name = "HP Envy 6055e Printer",
                            Price = 129m
                        },
                        new
                        {
                            Id = 23,
                            Name = "Apple AirPods Pro (2nd Gen)",
                            Price = 249m
                        },
                        new
                        {
                            Id = 24,
                            Name = "Samsung T7 Portable SSD 1TB",
                            Price = 109m
                        },
                        new
                        {
                            Id = 25,
                            Name = "Philips Hue Smart Bulb",
                            Price = 49m
                        },
                        new
                        {
                            Id = 26,
                            Name = "Instant Pot Duo 7-in-1",
                            Price = 89m
                        },
                        new
                        {
                            Id = 27,
                            Name = "Dyson V11 Vacuum Cleaner",
                            Price = 599m
                        },
                        new
                        {
                            Id = 28,
                            Name = "KitchenAid Stand Mixer",
                            Price = 429m
                        },
                        new
                        {
                            Id = 29,
                            Name = "Sony PlayStation DualSense Controller",
                            Price = 69m
                        },
                        new
                        {
                            Id = 30,
                            Name = "Google Nest Thermostat",
                            Price = 129m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
