// <auto-generated />
using DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DAL.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Coke",
                            Price = 2m
                        },
                        new
                        {
                            Id = 2,
                            Name = "Pepsi",
                            Price = 3m
                        },
                        new
                        {
                            Id = 3,
                            Name = "Purse",
                            Price = 100m
                        },
                        new
                        {
                            Id = 4,
                            Name = "Watch",
                            Price = 500m
                        },
                        new
                        {
                            Id = 5,
                            Name = "Phone",
                            Price = 400m
                        },
                        new
                        {
                            Id = 6,
                            Name = "Controller",
                            Price = 80m
                        },
                        new
                        {
                            Id = 7,
                            Name = "Bread",
                            Price = 3m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
